NAME = libft.a

SRC = ft_isalnum.c \
ft_isalpha.c \
ft_isascii.c \
ft_isdigit.c \
ft_isprint.c \
ft_iswspace.c \
ft_abs.c \
ft_strlen.c \
ft_memset.c \
ft_bzero.c \
ft_memcpy.c \
ft_memmove.c \
ft_strlcpy.c \
ft_strlcat.c \
ft_toupper.c \
ft_tolower.c \
ft_strchr.c \
ft_strrchr.c \
ft_strncmp.c \
ft_memchr.c \
ft_memcmp.c \
ft_strnstr.c \
ft_atoi.c \
ft_calloc.c \
ft_repl_substr.c \
ft_strdup.c \
ft_putchar_fd.c \
ft_putstr_fd.c \
ft_putnbr_fd.c \
ft_split.c \
ft_striteri.c \
ft_strjoin.c \
ft_strmapi.c \
ft_strndup.c \
ft_strtrim.c \
ft_substr.c \
ft_itoa.c \
ft_putendl_fd.c \
ft_putnbr_base.c \
ft_lstnew_bonus.c \
ft_lstadd_front_bonus.c \
ft_lstsize_bonus.c \
ft_lstlast_bonus.c \
ft_lstadd_back_bonus.c \
ft_lstclear_bonus.c \
ft_lstdelone_bonus.c \
ft_lstmap_bonus.c \
ft_lstiter_bonus.c \
ft_lst_delnode_bonus.c

FLAGS = -Wall -Wextra -Werror

BUILD_DIR	=	obj/

OBJ = $(addprefix $(BUILD_DIR), $(SRC:.c=.o))

RESET		=	"\033[0m"
YELLOW		=	"\033[0;33m"

all: $(BUILD_DIR) $(NAME)

$(BUILD_DIR):
	@mkdir $@

$(NAME): $(OBJ)
	@ar rc $(NAME) $(OBJ)

$(BUILD_DIR)%.o: $(SRC_DIR)%.c | $(BUILD_DIR)
	@printf $(YELLOW)"%-33.33s\r"$(RESET) $@
	@gcc $(FLAGS) -c $< -o $@

clean:
	@rm -rdf $(BUILD_DIR)
	
fclean: clean
	@rm -f $(NAME)

re: fclean all

.PHONY:
	all clean fclean re test bonus
